name: learn-github-actions
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        run: |
          # Pillow system requirements first:
          sudo apt-get install libjpeg8 zlib1g libfreetype6
          python3 -m pip install --upgrade -r requirements.txt
      - name: Check style
        run: python3 -m flake8
      - name: Run
        run: ./run.py
